#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon May 25 10:04:04 2020

@author: shihsir
"""

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df1 = pd.DataFrame({"Categorical":('A', 'B', 'C', 'D'), "Metric":(1,2,3,4)})
df2 = pd.DataFrame({"Categorical":('A', 'B', 'C', 'D'), "Metric":(5,6,7,8)})
df3 = pd.DataFrame({"Categorical":('A', 'B', 'C', 'D'), "Metric":(9,10,11,12)})
df4 = pd.DataFrame({"Categorical":('A', 'B', 'C', 'D'), "Metric":(13,14,15,16)})

df5 = pd.concat([df1, df2, df3, df4])
df6 = df5.reset_index()
df7 = df6.drop("index", axis=1)
df7["Categorical"] = pd.Categorical(df7["Categorical"])
df7.groupby('Categorical')['Metric'].mean()



os.chdir('/media/shihsir/HDD/Courses/Microclimates')
data = pd.read_csv('rcp85.climate.csv', sep=";", header=0, parse_dates=[0], index_col=0)
data_monthly = data.resample('M').mean()
data['pcp']
data_a = data_monthly['1960':'2005']
data_b = data_monthly['2043':'2100']

data_a_y = data_a.resample('Y').mean()
data_b_y = data_b.resample('Y').mean()

data[' pcp ']

#Plotting option 1
plt.plot(data_a_y.index, data_a_y.iloc[:,2], 'b')
plt.plot(data_a_y.index, data_a_y.iloc[:,1], 'b')
plt.plot(data_a_y.index, data_a_y.iloc[:,0], 'b')


#Plotting option 2

fig = plt.figure(figsize=(6,4))
sub1 = plt.subplot(311)
plt.plot(data_a_y.index,data_a_y.loc["pcp"])
sub2 = plt.subplot(312)
plt.plot(data_a_y.index, data_a_y.iloc[:,1])
sub3 = plt.subplot(313)
plt.plot(data_a_y.index, data_a_y.iloc[:,2])
fig.tight_layout()

fig = plt.figure(figsize=(6,4))
sub1 = plt.subplot(311)
plt.plot(data_b_y.index,data_b_y.iloc[:,0])
sub2 = plt.subplot(312)
plt.plot(data_b_y.index, data_b_y.iloc[:,1])
sub3 = plt.subplot(313)
plt.plot(data_b_y.index, data_b_y.iloc[:,2])
fig.tight_layout()





















