#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun May 17 16:22:55 2020

@author: Shahadat Hossain, 3847363
"""
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

os.chdir('/media/shihsir/HDD/Courses/Microclimates')
data = pd.read_csv('Ex02_data.csv', sep=";", header= 0, parse_dates=[0], index_col=0)

#Min Values
tmax = data.loc[:, 'Tmax'].min()
tmin = data.loc[:, 'Tmin'].min()
rrmin = data.loc[:, 'RR'].min()

#Max values
Tmax = data.loc[:, 'Tmax'].max()
Tmin = data.loc[:, 'Tmin'].max()
rrmax = data.loc[:, 'RR'].max()

data_mean = data.resample('M').mean()

print(data.Tmax)

#Anomalies
tmaxanom = data.Tmax - data.Tmax.mean()
tminanom = data.Tmin - data.Tmin.mean()
yearlytmax = tmaxanom.resample('1y').mean()
yearlytmin= tminanom.resample("1y").mean()


fix,ax=plt.subplots(3,1,figsize=(16,10))
plt.style.use("seaborn")
ax[0].plot(data_mean.index,data_mean["Tmax"],label="MAX Temperature",color="r",linestyle="-")
ax[0].set_ylabel("MaxT")
ax[1].plot(data_mean.index,data_mean["Tmin"],label="Min Temperature",color="g",linestyle="-")
ax[1].set_ylabel("MinT")
ax[2].plot(data_mean.index,data_mean["RR"],label="RR",linestyle="-")
ax[2].set_ylabel("RR")
plt.show()


fix,ax=plt.subplots(2,1,figsize=(16,10))
ax[0].plot(yearlytmax,color="r",lw=2)
ax[0].set_ylabel("Max Temperature anomaly")
ax[1].plot(yearlytmin,color="g",lw=2)
ax[1].set_ylabel("Min Temperature anomaly")
